[package]
name = "axiom_halo2_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm = "0.9.0"
halo2_proofs_axiom = { git = "https://github.com/axiom-crypto/halo2.git", tag = "v2023_01_17", package = "halo2_proofs" }
rand = "0.8"
ark-std = "0.4"
dirs = "3.0"
downloader = { version = "0.2.7", default-features = false, features = [
    "rustls-tls",
] }
indicatif = "0.15.0"
