[package]
name = "halo2_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

acvm = "0.14.1"
bincode = "1.3.3"
bytesize = "1.2"
rand = "0.8"
reqwest = { version = "0.11.16", default-features = false, features = [
    "stream",
    "rustls-tls",
] }
serde = { version = "1.0.136", features = ["derive"] }
tokio = "1.0"
futures-util = "0.3.14"
thiserror = "1.0.21"

# zcash
zcash_halo2_proofs = { package = "halo2_proofs", version = "0.3.0", optional = true }

# pse
# pse_halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", package = "halo2_proofs", tag = "v2023_04_20", optional = true }
pse_halo2wrong = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", package = "halo2wrong", tag = "v2023_04_20", features = [
    "circuit-params",
], optional = true }
pse_maingate = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", package = "maingate", tag = "v2023_04_20", features = [
    "circuit-params",
], optional = true }
pse_ecdsa = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", package = "ecdsa", tag = "v2023_04_20", features = [
    "circuit-params",
], optional = true }
pse_ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", package = "ecc", tag = "v2023_04_20", features = [
    "circuit-params",
], optional = true }
pse_snark_verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier", package = "snark-verifier", tag = "v2023_04_20", features = [
    "halo2_circuit_params",
], optional = true }
# pse_zkevm_circuit = { git = "https://github.com/privacy-scaling-explorations/zkevm-circuits", package = "zkevm-circuits", tag = "v0.3.1", optional = true }

# axiom
halo2-base = { git = "https://github.com/axiom-crypto/halo2-lib", branch = "release-0.3.0", optional = true }
snark-verifier = { git = "https://github.com/axiom-crypto/snark-verifier.git", branch = "release-0.1.1", optional = true }
halo2-ecc = { git = "https://github.com/axiom-crypto/halo2-lib", branch = "release-0.3.0", optional = true }
# zkevm-keccak = { git = "https://github.com/axiom-crypto/halo2-lib", branch = "release-0.3.0", optional = true }

[dev-dependencies]
serde_json = "1.0.68"

[features]
default = ["pse_halo2"]
zcash_halo2 = ["dep:zcash_halo2_proofs"]
pse_halo2 = [
    "dep:pse_halo2wrong",
    "dep:pse_maingate",
    "dep:pse_ecdsa",
    "dep:pse_ecc",
    "dep:pse_snark_verifier",
    # "dep:pse_zkevm_circuit",
]
axiom_halo2 = ["dep:halo2-base", "dep:snark-verifier", "dep:halo2-ecc"]
