name: cargo fmt & clippy

on:
  push:
    branches: [master]
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly-2022-10-28
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add rustfmt && rustup component add clippy
      - run: cargo fmt --check
      - run: cargo clippy
